version: "3.9"

services:

  database:
    image: 'postgres:latest'
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./config/.env
    volumes:
      - data:/var/lib/postgresql/data/

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./config/.env
    depends_on:
      - database
    networks:
      - default
    ports:
      - "8080:8080"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - ./config/.env
    ports:
      - "5050:80"
    volumes:
      - ./config/db.json:/pgadmin4/servers.json

volumes:
  data:
